macro(set_output_dir_structure)

if(NOT DEFINED OUTPUT_DIR_SET)
	include(GNUInstallDirs RESULT_VARIABLE OUTPUT_DIR_SET)

	foreach(CONFIG ${CMAKE_CONFIGURATION_TYPES})
		string(TOUPPER "${CONFIG}" CONFIG_SUFFIX)

		set(CONFIG_RUNTIME_OUTPUT_DIRECTORY "CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG_SUFFIX}")
		set("${CONFIG_RUNTIME_OUTPUT_DIRECTORY}" "${CMAKE_BINARY_DIR}/${CONFIG}/${CMAKE_INSTALL_BINDIR}")
		set(CONFIG_LIBRARY_OUTPUT_DIRECTORY "CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG_SUFFIX}")
		set("${CONFIG_LIBRARY_OUTPUT_DIRECTORY}" "${CMAKE_BINARY_DIR}/${CONFIG}/${CMAKE_INSTALL_LIBDIR}")
		set(CONFIG_ARCHIVE_OUTPUT_DIRECTORY "CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG_SUFFIX}")
		set("${CONFIG_ARCHIVE_OUTPUT_DIRECTORY}" "${CMAKE_BINARY_DIR}/${CONFIG}/${CMAKE_INSTALL_LIBDIR}")
	endforeach()
endif()

endmacro()
